### ISSUE TITLE
The shell doesn't accept input?

### ISSUE THREAD

**Issue by jessearmand** [Shopify/superdb#10]
I've checked out develop, and related to issue #9, I disabled the suggestion window. However the shell doesn't seem to process the input to the iPhone Simulator.

![Screen Shot 2013-01-22 at 12 19 10 PM](https://f.cloud.github.com/assets/67312/85296/3758d750-644b-11e2-95cd-4d46693aa36f.png)

**Comment by jessearmand** [comment]
Weird, it stops just before this line:

```
[self.networkClient requestWithCommand:choppedCommand input:choppedInput responseHandler:^(SuperNetworkMessage *response) { 

...
}
```

**Comment by kemenaran** [comment]
I had this issue when the shell wasn't bound to an iOS application. I clicked the "Shell" button rather that double-clicking the app name, and has exactly the same results.

**Comment by jessearmand** [comment]
Hmm.. interesting. I guess it's a usability issue. What's that "Shell" button is for actually?

**Comment by jbrennan** [comment]
Ah yes, I should have put this in the readme. 

The shell button is there just for me, it's a way for me to test shell features, but it won't work with actual apps this way. That's my bad for not including this in the readme.

(I don't have access to the original repo any long since I've left Shopify but I will fix this up and make a pull request from my repo)
