### ISSUE TITLE
rect is broken

### ISSUE THREAD

**Issue by Sohojoe** [Shopify/superdb#22]
r := 1<>2 extent:2<>3 is giving the following "error: an instance of NSConcreteValue does not respond to "extent:""

Looks like something got broken with the switch from NSPoint (etc) to CGPoint for iOS

**Comment by jbrennan** [comment]
Yeah I’ve noticed that too. I think you might need to make sure to add the `-Obj` linker flag because those are added as category methods, which won’t load without that flag.

Failing that, I think I’ve made a Geometry class somewhere which has methods for dealing with basic geometry types. That might work as a hack.

**Comment by Sohojoe** [comment]
doh - I hadn't added the -ObjC flag in step 6 if the install steps - it's fixed now and works
